version: '3'

services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: always
    ports:
      - 4822:4822
    environment:
      - GUACD_LOG_LEVEL=debug

  mysql:
    image: ir0cn/mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./dbdata:/var/lib/mysql





