version: '2'

services:
  registry:
    restart: always
    image: registry:2
    volumes:
      - ./data:/var/lib/registry

#  ldap:
#    restart: always
#    image: osixia/openldap:latest

  nginx:
    restart: always
    image: ir0cn/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
    environment:
      SERVER_NAME: ir0.cn,*.ir0.cn
      PROXY_BACKEND: registry:5000

